### ISSUE TITLE
No RPi 3B at all, just RPi 3B+?

### ISSUE THREAD

**Issue by generic-beat-detector** [autorope/donkeycar#1000]
Apparently, the "relevant" difference between RPi 3B and 3B+ is the CPU clock (1.2GHz vs. 1.4GHz). I don't think the other differences in specs e.g. Ethernet (100Base vs. 1000Base), and Wi-Fi (802.11b/g/n vs. 802.11ac) matter too much for the on-board the autopilot. So, while a 3B+ would be optimal, 3B should still work, right?

**Comment by Ezward** [comment]
It should work. The inference rate will be slower.
