### ISSUE TITLE
Creating 'donkey' environment from ubuntu.yml takes forever

### ISSUE THREAD

**Issue by nabanita-** [autorope/donkeycar#1008]
I am trying to setup the donkey environment in my desktop (Ubuntu18.04.6 LTS) following the instructions [here](https://docs.robocarstore.com/guide/host_pc/setup_ubuntu/). But solving environment is taking forever. 
![donkey-issue](https://user-images.githubusercontent.com/10485934/162180167-9aae11ee-558d-4618-952e-8aa395dcfb91.png)

I also tried by setting channel_priority as strict (`conda config --set channel_priority strict`) but it resulted in a huge number of conflicts, so I ditched that route.
 

Is there something that I am missing? I am using the yaml file in the main branch of this github repository. 

Here is the yaml file content for easy reference: 

```
name: donkey

channels:
  - defaults
  - conda-forge
  - pytorch
  
dependencies:
  - python=3.7
  - h5py
  - pillow
  - opencv
  - matplotlib
  - tornado
  - docopt
  - pandas
  - pylint
  - pytest
  - pytest-cov
  - codecov
  - pip
  - imgaug
  - progress
  - moviepy
  - paho-mqtt
  - PrettyTable
  - pyfiglet
  - mypy
  - pytorch=1.7.1
  - torchvision
  - torchaudio
  - pytorch-lightning
  - numpy
  - psutil
  - kivy=2.0.0
  - plotly
  - pyyaml
  - tensorflow=2.2.0
  - fastai
  - pip:
    - git+https://github.com/autorope/keras-vis.git
    - simple-pid
    - opencv-python-headless
```

**Comment by c1505** [comment]
@nabanita- I don't know why the conda install takes so long, but you aren't alone in that experience of it taking a very long time or hanging.  I think mamba should be the recommended install .  There is a PR for docs changes for that here that I reviewed https://github.com/autorope/donkeydocs/pull/37 .  I don't have write access to merge it though.  

Just noticing that the docs you are using are on a separate domain and use a separate github repository than what I have used https://docs.donkeycar.com/ .  Both the code and docs have not been updated in about 9 months for the robocarstore org.  I am not sure who has access to that repo and how much they are in the donkeycar discord.  I would suggest using this repository for code and the previously mentioned link for docs.

**Comment by Ezward** [comment]
I have an experimental branch that has a bash script for installing on unbuntu.  Once you clone/checkout the branch, the run `./install.ubuntu.pip.sh`  https://github.com/autorope/donkeycar/tree/990-ubuntu-install-script

**Comment by victorjnpires** [comment]
@nabanita- I've also had issues with conda taking forever on conflict resolution, and mamba was the solution. This is my simplified yml:

```
name: donkey

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - h5py
  - pillow
  - opencv
  - matplotlib
  - tornado
  - docopt
  - pandas
  - pylint
  - pytest
  - pytest-cov
  - codecov
  - pip
  - imgaug
  - progress
  - moviepy
  - paho-mqtt
  - PrettyTable
  - pyfiglet
  - mypy
  - numpy
  - psutil
  - kivy=2
  - plotly
  - pyyaml
  - tensorflow-gpu=2.7
  - pip:
    - git+https://github.com/autorope/keras-vis.git
    - simple-pid
    - opencv-python-headless
```

**Comment by nabanita-** [comment]
> @nabanita- I don't know why the conda install takes so long, but you aren't alone in that experience of it taking a very long time or hanging. I think mamba should be the recommended install . There is a PR for docs changes for that here that I reviewed [autorope/donkeydocs#37](https://github.com/autorope/donkeydocs/pull/37) . I don't have write access to merge it though.
> 
> Just noticing that the docs you are using are on a separate domain and use a separate github repository than what I have used https://docs.donkeycar.com/ . Both the code and docs have not been updated in about 9 months for the robocarstore org. I am not sure who has access to that repo and how much they are in the donkeycar discord. I would suggest using this repository for code and the previously mentioned link for docs.

I hadn't noticed the difference in domains! Thank you, I will keep that in mind. Solved my problem ^.^

**Comment by DocGarbanzo** [comment]
The PR https://github.com/autorope/donkeydocs/pull/37 got merged, so closing this now.
