### ISSUE TITLE
KeyError: 'user/angle'

### ISSUE THREAD

**Issue by Ahrovan** [autorope/donkeycar#1103]
Command : `donkey train --tub ./data --model ./models/mypilot.h5`

ERROR : `2023-02-26 22:35:30.444913: W tensorflow/core/framework/op_kernel.cc:1755] Unknown: KeyError: 'user/angle'`

How to solve:

- change manifest.json and catalog_x.catalog 
 all "user/steering" >> "user/angle"

Why occurred ? donkey car web controller saved all steering values as "user/angle" not "user/steering"
![image](https://user-images.githubusercontent.com/5772832/221432219-712f8ad1-0537-48c2-88c9-3561044852f8.png)

**Comment by Ezward** [comment]
This is my error.  I just merged a change that renamed 'user/angle' to 'user/steering' as part of a larger change, forgetting that this would obsolete old data.  I will work on a fix immediately.

**Comment by Ezward** [comment]
@Ahrovan I've made a change in this branch; https://github.com/autorope/donkeycar/tree/1104-fix-user-angle-in-deep-learning  It will now again save steering data with the 'user/angle' label ratehr than 'user/steering'  However this does not fix data that was saved with 'user/steering',but you say you have a work-around for data that was erroneously saved using 'user/steering':
- To fix data saved with 'user/steering', change manifest.json and catalog_x.catalog all "user/steering" >> "user/angle"

Please give the branch a test and let me know here is this fixes the data recording issue.  Thanks and sorry for the trouble.

**Comment by Ezward** [comment]
See PR https://github.com/autorope/donkeycar/pull/1105 for a fix

**Comment by Ezward** [comment]
That PR merged.  I've tested in by collecting data, training and driving on autopilot.
