### ISSUE TITLE
train done -Always no result

### ISSUE THREAD

**Issue by Ahrovan** [autorope/donkeycar#1104]
using donkey v4.4.dev6 ...

I have not been able to train and run for several days. I doubted my data. Finally, I repeated the work of train with your data

- [sim_warehouse_manual.tar.gz](https://github.com/autorope/donkey_datasets/blob/master/large_dataset/sim_warehouse_manual.tar.gz)
- myconfig.py not changed just added three lines
```
DONKEY_GYM = True
DONKEY_SIM_PATH = "...../projects/DonkeySimWin/donkey_sim.exe"
DONKEY_GYM_ENV_NAME = "donkey-generated-track-v0"
```
- Pilot throttle and angle always is constant or wrong
- please check and provide a solution.

![sim-tub2-min](https://user-images.githubusercontent.com/5772832/221435093-c8f9a8ff-29c3-48ae-be09-4f8d89b8d160.gif)
![sim-tub-min](https://user-images.githubusercontent.com/5772832/221435097-ff0587ff-9684-444f-8e10-7ddcd4e2c3a7.gif)

**Comment by Ezward** [comment]
I've made a change to the deep learning template that caused this.  It is saving steering data as 'user/steering' rather than 'user/angle'.  I've made a fix in this branch so that future data will again be recording as 'user/angle' https://github.com/autorope/donkeycar/tree/1104-fix-user-angle-in-deep-learning  Please give that a try and let me know if it is recording data correctly.  I'll look into how to fix the data that has been recorded as 'user/steering'

**Comment by Ezward** [comment]
@Ahrovan Given the 'user/steering'->'user/angle' bug that was just fixed, can you checkout the latest main and rewrite your mycar folder (or whatever folder you use for the donkeycar application).  So from the root of your donkeycar repo:
```
git checkout main
donkey createcar --overwrite --path=<path-to-your-mycar>
```
and give it another try.

**Comment by Ezward** [comment]
PS: I gathered data, trained and ran autopilot using the new code.  Remember that the steering data is labelled as 'user/angle' so if you changed that to 'user/steering' then you should change it back.

**Comment by Ahrovan** [comment]
[sim_warehouse_manual.tar.gz](https://github.com/autorope/donkey_datasets/blob/master/large_dataset/sim_warehouse_manual.tar.gz) extracted again. 

![sim-tub](https://user-images.githubusercontent.com/5772832/221480980-478f2b4f-d020-4c3d-a8c2-05953fac863a.gif)

**Comment by Ezward** [comment]
@Ahrovan Can you try training using the command line?  See https://docs.donkeycar.com/guide/deep_learning/train_autopilot/#train-a-model  That way we can see if it is DonkeyUI or the donkeycar train command itself.

PS: I trained a model yesterday from the command line on a Mac and it worked file.

**Comment by Ezward** [comment]
@Ahrovan Also are you training a 'linear' model but running it as a 'categorical' model; that is what I see in the screen captures above.

**Comment by Ahrovan** [comment]
@Ezward no, but is linear. Problem just related to recording. I know but need to same

**Comment by Ahrovan** [comment]
@Ezward @DocGarbanzo 

Python 3.7.16 | donkey v4.4.dev6 | tensorflow '2.2.0' | windows | linear model | Created New Conda Env today

- train always finish without any Error.
`INFO:donkeycar.parts.interpreter:Convert model C:\Users\Hadi\workspace\mycar\models\mypilot.h5 to TFLite C:\Users\Hadi\workspace\mycar\models\mypilot.tfl
`
- tested with donkey ui and command line
- [sim_warehouse_manual.tar.gz](https://github.com/autorope/donkey_datasets/blob/master/large_dataset/sim_warehouse_manual.tar.gz) used
- [h5 file ] 9,661 KB after train completed

![1](https://user-images.githubusercontent.com/5772832/221811530-d757ffd3-3697-4b50-8e05-84d4b6fbb7a8.gif)

![mypilot](https://user-images.githubusercontent.com/5772832/221812287-eaf7b5b0-ee92-4ee2-b42d-2100da3d0cde.png)

**Comment by Ezward** [comment]
@Ahrovan that does look wrong.  Can you try running tubplot with your model and data to see what it outputs; https://docs.donkeycar.com/utility/donkey/#plot-predictions

**Comment by Ezward** [comment]
Please also check your data again; I believe you renamed 'user/angle' to 'user/steering';  if you did you need to restore it to 'user/angle'.

**Comment by Ahrovan** [comment]
[sim_warehouse_manual.tar.gz](https://github.com/autorope/donkey_datasets/blob/master/large_dataset/sim_warehouse_manual.tar.gz) extracted without any change.  
![image](https://user-images.githubusercontent.com/5772832/221962695-63e7555b-a978-4cbc-9b6d-dde63069661b.png)
**'user/angle' exist.**

**Comment by Ahrovan** [comment]
@Ezward The problem is related to train with gpu. If train operation is done with cpu, the problem will be solved.

- No error is reported during tarin with GPU. But the result has a fixed value.
- cuda is installed correctly.
- cudnn is installed correctly.
- Our GPU is from Nvidia series.
**- Important >> This problem occurred in Jetson Device Like NX, Nano** and PC, Windows and Ubuntu, WSL2

**Comment by Ezward** [comment]
@Ahrovan can you try to train with an earlier version of donkeycar so we can see if it is a recently introduced bug?  Maybe checkout tag `4.3.6.2` or `4.4.0`

**Comment by Ahrovan** [comment]
Report - donkey v4.4.dev6 worked on Jetson NX - Trained with GPU

**Comment by Ezward** [comment]
to summarize
- train on cpu works
- train with v4.4.dev6 on Jetson NX GPU works
- train with TensorFlow version 2.3.1 | donkey v4.4.dev6 | windows | h5 model produces constant throttle/angle.  Assume training using GPU?
- train with Python 3.7.16 | donkey v4.4.dev6 | tensorflow '2.2.0' | windows | h5 model produces constant throttle/angle.  Assume training using GPU?

Is that correct?

On the failing system can you train using the command line and copy the console output here?

**Comment by Ahrovan** [comment]
- donkey ui with GPU = wrong pilot play (Video first part)
- donkey ui without GPU = True result (Video second part)

This shows that the model has no problem. Only the ui display has a problem. I have tested this model on the robot. Robot runs without problems

![ui-with gpu + without gui-min](https://user-images.githubusercontent.com/5772832/222793222-46167693-4f3e-4998-9993-d8497bd52d52.gif)

**Comment by Ezward** [comment]
Except that you also did a tubplot and it also showed constant throttle and steering.

**Comment by Ahrovan** [comment]
![3234](https://user-images.githubusercontent.com/5772832/222885893-5c410ec0-9e73-4dc3-a525-c608c0ad669c.gif)
[log.txt](https://github.com/autorope/donkeycar/files/10887869/log.txt)

**Comment by Ezward** [comment]
I don't understand what is happening in the prior comment; can you add an explanation?

**Comment by Ezward** [comment]
Maybe you are saying one of the modes is always getting that bad record NaN error?  And a white screen.  Is that the same thing that was going on before?  It looks different.

**Comment by Ahrovan** [comment]
yes, white screen is related model trained with GPU always getting bad record NaN error. yes, i don't know

**Comment by Ezward** [comment]
@DocGarbanzo have you seen this issue before in the DonkeyUI?  Do you know what this might be?

**Comment by Ahrovan** [comment]
Problem solved. 
cudnn 8.1 CUDA 11.2 TensorFlow 2.5 (CUDA >= 11)
now I am working on compatibility issues on Host and Jetson platform.

**Comment by Ezward** [comment]
Great. I am glad you have a solution.  Closing this issue.
