### ISSUE TITLE
Add feature - connect to a new simulator

### ISSUE THREAD

**Issue by Ahrovan** [autorope/donkeycar#1117]
We want to connect to another simulator. This simulator has several simple methods: connect, setSteering, setSpeed, etc. Just please guide to add this feature in donkeycar code.

**Comment by Maximellerbach** [comment]
Could you be more specific about which simulator?

**Comment by Ahrovan** [comment]
https://github.com/AvisEngine/AVIS-Engine-Python-API

AVIS Engine Python API

**Comment by Ezward** [comment]
@Maximellerbach I don't think we should do this.  I don't think we want to support a 3rd party api that will change over time as AWS changes their simulator.  We are open source, so @Ahrovan can write the necessary Donkey part it an keep it in a personal repo.

**Comment by Maximellerbach** [comment]
@Ezward yep, that's my point of view too

**Comment by Ezward** [comment]
Ok, I'm closing this as won't do.  @Ahrovan we can provide support for you in the donkey discord if you choose to do this work.
