### ISSUE TITLE
donkey createcar --path ~/mycar using donkey v3.1.0 ... Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by 0jeetparmar0** [autorope/donkeycar#1156]
i am using jetson nano 4gb 
while creating donkey createcar --path ~/mycar
i got mesg like this 
donkey createcar --path ~/mycar
using donkey v3.1.0 ...
Illegal instruction (core dumped)
using jetpack 4.6.1

**Comment by TCIII** [comment]
@0jeetparmar0,
You will be better off posting your issue with DC 3.1.0 on the Donkey Car Discord Discussion Forum as DC 3.1.0 is so far out of date that your issue will not receive the attention it requires here for a speedy resolution.
 TCIII

**Comment by 0jeetparmar0** [comment]
Ohk thanks 👍🙏
Jeet
