### ISSUE TITLE
Recursion error for opening donkey ui

### ISSUE THREAD

**Issue by Kim0189826** [autorope/donkeycar#1171]
Why does it happened after i follow all the steps in donkeycar website? Im using sublinux

It said that i had recursionerror ?

**Comment by TCIII** [comment]
@Kim0189826,
The [IoT](https://rollbar.com/blog/python-recursionerror/) is your friend.
Please paste the error you are seeing so that we can view it and help you.

**Comment by Ezward** [comment]
@Kim0189826 what is sublinux?

**Comment by DocGarbanzo** [comment]
I have seen that error too recently. Did you perform the user install (via pip, which would give you DC 5.0.0) or the developer install (using git clone and editable install, which would give you DC 5.1.dev1)? If you did the latter, try to delete all pre-compiled python files (.pyc) and see if that helps. Otherwise, wait a couple of days when we have pushed a new 5.1 release to pypi and then do the (recommended) user install.

**Comment by Kim0189826** [comment]
@DocGarbanzo i perform the developer install, so what should i do to address this recursionerror issue for my donkey ui? Additional question, when i train my tubdata for autopilot model, does it still provide h5file ?

**Comment by DocGarbanzo** [comment]
> @DocGarbanzo i perform the developer install, so what should i do to address this recursionerror issue for my donkey ui? Additional question, when i train my tubdata for autopilot model, does it still provide h5file ?

@Kim0189826 - I see the same recursion error when running the UI on the RPi. It should not show up when you run with your PC installation (no matter if user or developer install). Models are not saved in the legacy keras h5 format any longer, but rather in tensorflow savedmodel format. However, for all purposes using the tflite format is better. 

I see that the recursion error is gone when using my new version of the refactored UI, so I will create a PR soon which should resolve the issue on RPi.

**Comment by Kim0189826** [comment]
> > @DocGarbanzo i perform the developer install, so what should i do to address this recursionerror issue for my donkey ui? Additional question, when i train my tubdata for autopilot model, does it still provide h5file ?
> 
> @Kim0189826 - I see the same recursion error when running the UI on the RPi. It should not show up when you run with your PC installation (no matter if user or developer install). Models are not saved in the legacy keras h5 format any longer, but rather in tensorflow savedmodel format. However, for all purposes using the tflite format is better.
> 
> I see that the recursion error is gone when using my new version of the refactored UI, so I will create a PR soon which should resolve the issue on RPi.

What’s the coding for using tflite in our pi for autopilot after we trained the tub data? Cause as i know before im using h5 such as command, python manage.py drive - -model ~/mycar/models/pilot 23-05-11 22.h5, and itll start the donkey monitor for running the autopilot.
![Uploading FC41E104-13EE-4AA4-8CC1-FEA8BC2C661E.jpeg…]()

**Comment by Kim0189826** [comment]
Like this for an example.
![C3664D37-3C70-4C15-8603-FDFB21D90CDA](https://github.com/autorope/donkeycar/assets/165549082/a598ae8a-eb98-40e1-a4e5-bd064146d179)

**Comment by Kim0189826** [comment]
@DocGarbanzo hopefully you can help to address my issue 🥲

**Comment by half-freez** [comment]
> Why does it happened after i follow all the steps in donkeycar website? Im using sublinux
> 
> It said that i had recursionerror ?

Yes, I have the same error, after install using 3 different pc. Using Ubuntu, and also in windows, and also in wsl

**Comment by half-freez** [comment]
![IMG_20240417_225722](https://github.com/autorope/donkeycar/assets/167308896/4141bf4b-6ce4-4e37-b92d-6d3b2c0b8aab)

**Comment by Kim0189826** [comment]
> > Why does it happened after i follow all the steps in donkeycar website? Im using sublinux
> > It said that i had recursionerror ?
> 
> Yes, I have the same error, after install using 3 different pc. Using Ubuntu, and also in windows, and also in wsl 

checkout the latest ui_updated pr. It should resolve the issue.

**Comment by half-freez** [comment]
how can i perform the ui_updated pr
