### ISSUE TITLE
Autopilot

### ISSUE THREAD

**Issue by Kim0189826** [autorope/donkeycar#1174]
Im having a problem with this issue to run autopilot for my donkeycar 

![A79B3E8E-E61A-4ED0-B52F-E97EB27CDAD7](https://github.com/autorope/donkeycar/assets/165549082/a8f16ade-831b-465b-8c61-5e6f667b0322)
![25197CC5-1E6D-4E22-9092-17A7EAAD63D5](https://github.com/autorope/donkeycar/assets/165549082/66684887-d420-4ae5-983e-4cff60f08e62)

Before this im using .h5 and it works, but now h5 no longer being used then ill try change it with tflite file. But it failed, can you addres this issue for me?

**Comment by TCIII** [comment]
@Kim0189826,
Why don't you do a copy and paste instead of trying to take photographs of your PC screen?
