### ISSUE TITLE
running manage.py drive get "Illegal instruction" error

### ISSUE THREAD

**Issue by drtechga** [autorope/donkeycar#238]
When i try to start the "python manage.py drive" command from the pre-built SD card image i get this as the output:
using donkey v2.2.1 ...
Using TensorFlow backend.
Illegal instruction
(dk) pi@d2:~/d2 $

**Comment by wroscoe** [comment]
What version of Pi?

**Comment by drtechga** [comment]
B+ v1.2

**Comment by wroscoe** [comment]
Yep. Still working on image that is tested on B+. This week hopefully.

**Comment by wroscoe** [comment]
donkey now works on B+
