### ISSUE TITLE
Illegal array length, must be 15

### ISSUE THREAD

**Issue by NikulausRui** [autorope/donkeycar#308]
When I run python manage.py drive --model ./models/mypilot,and then choose LocalAngle,this mistake was occured:

Traceback (most recent call last):
File "manage.py", line 190, in 
drive(cfg, model_path = args['--model'], use_joystick=args['--js'], use_chaos=args['--chaos'])
File "manage.py", line 131, in drive
max_loop_count=cfg.MAX_LOOPS)
File "/home/pi/env/lib/python3.5/site-packages/donkeycar/vehicle.py", line 93, in start
self.update_parts()
File "/home/pi/env/lib/python3.5/site-packages/donkeycar/vehicle.py", line 129, in update_parts
outputs = p.run(*inputs)
File "/home/pi/env/lib/python3.5/site-packages/donkeycar/parts/keras.py", line 75, in run
angle_unbinned = util.data.linear_unbin(angle_binned[0])
File "/home/pi/env/lib/python3.5/site-packages/donkeycar/util/data.py", line 38, in linear_unbin
raise ValueError('Illegal array length, must be 15')
ValueError: Illegal array length, must be 15

Every time I can only run python manage.py drive and then choose LocalAngle,but it does not achieve the desired result.

**Comment by NikulausRui** [comment]
check manage.py.change drive and train use same model(categorical or linear)-------- 原始邮件 --------主题：Re: [wroscoe/donkey] Illegal array length, must be 15 (#308)发件人：easonzrq 收件人：wroscoe/donkey 抄送：NikulausRui ,State change I have the same question.
How do you fix it ?can you tell me
3Q

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wroscoe/donkey","title":"wroscoe/donkey","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/wroscoe/donkey"}},"updates":{"snippets":[{"icon":"PERSON","message":"@easonzrq in #308: I have the same question.\r\nHow do you fix it ?can you tell me \r\n3Q"}],"action":{"name":"View Issue","url":"https://github.com/wroscoe/donkey/issues/308#issuecomment-430916478"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/wroscoe/donkey/issues/308#issuecomment-430916478",
"url": "https://github.com/wroscoe/donkey/issues/308#issuecomment-430916478",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [wroscoe/donkey] Illegal array length, must be 15 (#308)",
"sections": [
{
"text": "",
"activityTitle": "**easonzrq**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@easonzrq",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"wroscoe/donkey\",\n\"issueId\": 308,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/wroscoe/donkey/issues/308#issuecomment-430916478"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 375088529\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by easonzrq** [comment]
sorry,i cant find where to change the mode.can you tell me ?

**Comment by easonzrq** [comment]
> check manage.py.change drive and train use same model(categorical or linear)-------- 原始邮件 --------主题：Re: [wroscoe/donkey] Illegal array length, must be 15 (#308)发件人：easonzrq 收件人：wroscoe/donkey 抄送：NikulausRui ,State change I have the same question. How do you fix it ?can you tell me 3Q —You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread. {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wroscoe/donkey","title":"wroscoe/donkey","subtitle":"GitHub repository","main_image_url":"[https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open](https://assets-cdn.github.com/images/email/message_cards/header.png%22,%22avatar_image_url%22:%22https://assets-cdn.github.com/images/email/message_cards/avatar.png%22,%22action%22:%7B%22name%22:%22Open) in GitHub","url":"[https://github.com/wroscoe/donkey"}},"updates":{"snippets":[{"icon":"PERSON","message":"@easonzrq](https://github.com/wroscoe/donkey%22%7D%7D,%22updates%22:%7B%22snippets%22:%5B%7B%22icon%22:%22PERSON%22,%22message%22:%22@easonzrq) in #308: I have the same question.\r\nHow do you fix it ?can you tell me \r\n3Q"}],"action":{"name":"View Issue","url":"[#308 (comment)](https://github.com/wroscoe/donkey/issues/308#issuecomment-430916478)"}}} [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#308 (comment)](https://github.com/wroscoe/donkey/issues/308#issuecomment-430916478)", "url": "[#308 (comment)](https://github.com/wroscoe/donkey/issues/308#issuecomment-430916478)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } }, { "@type": "MessageCard", "@context": "http://schema.org/extensions", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [wroscoe/donkey] Illegal array length, must be 15 (#308)", "sections": [ { "text": "", "activityTitle": "**easonzrq**", "activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png", "activitySubtitle": "@easonzrq", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"wroscoe/donkey\",\n\"issueId\": 308,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "targets": [ { "os": "default", "uri": "[#308 (comment)](https://github.com/wroscoe/donkey/issues/308#issuecomment-430916478)" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 375088529\n}" } ], "themeColor": "26292E" } ]

sorry,i cant find where to change the mode.can you tell me ?

**Comment by NikulausRui** [comment]
> > check manage.py.change drive and train use same model(categorical or linear)-------- 原始邮件 --------主题：Re: [wroscoe/donkey] Illegal array length, must be 15 (#308)发件人：easonzrq 收件人：wroscoe/donkey 抄送：NikulausRui ,State change I have the same question. How do you fix it ?can you tell me 3Q —You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread. {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wroscoe/donkey","title":"wroscoe/donkey","subtitle":"GitHub repository","main_image_url":"[https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open](https://assets-cdn.github.com/images/email/message_cards/header.png%22,%22avatar_image_url%22:%22https://assets-cdn.github.com/images/email/message_cards/avatar.png%22,%22action%22:%7B%22name%22:%22Open) in GitHub","url":"[https://github.com/wroscoe/donkey"}},"updates":{"snippets":[{"icon":"PERSON","message":"@easonzrq](https://github.com/wroscoe/donkey%22%7D%7D,%22updates%22:%7B%22snippets%22:%5B%7B%22icon%22:%22PERSON%22,%22message%22:%22@easonzrq) in #308: I have the same question.\r\nHow do you fix it ?can you tell me \r\n3Q"}],"action":{"name":"View Issue","url":"[#308 (comment)](https://github.com/wroscoe/donkey/issues/308#issuecomment-430916478)"}}} [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#308 (comment)](https://github.com/wroscoe/donkey/issues/308#issuecomment-430916478)", "url": "[#308 (comment)](https://github.com/wroscoe/donkey/issues/308#issuecomment-430916478)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } }, { "@type": "MessageCard", "@context": "http://schema.org/extensions", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [wroscoe/donkey] Illegal array length, must be 15 (#308)", "sections": [ { "text": "", "activityTitle": "**easonzrq**", "activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png", "activitySubtitle": "@easonzrq", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n"commandName": "IssueComment",\n"repositoryFullName": "wroscoe/donkey",\n"issueId": 308,\n"IssueComment": "{{IssueComment.value}}"\n}" } ] }, { "targets": [ { "os": "default", "uri": "[#308 (comment)](https://github.com/wroscoe/donkey/issues/308#issuecomment-430916478)" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n"commandName": "MuteNotification",\n"threadId": 375088529\n}" } ], "themeColor": "26292E" } ]
> 
> sorry,i cant find where to change the mode.can you tell me ?



> > check manage.py.change drive and train use same model(categorical or linear)-------- 原始邮件 --------主题：Re: [wroscoe/donkey] Illegal array length, must be 15 (#308)发件人：easonzrq 收件人：wroscoe/donkey 抄送：NikulausRui ,State change I have the same question. How do you fix it ?can you tell me 3Q —You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread. {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wroscoe/donkey","title":"wroscoe/donkey","subtitle":"GitHub repository","main_image_url":"[https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open](https://assets-cdn.github.com/images/email/message_cards/header.png%22,%22avatar_image_url%22:%22https://assets-cdn.github.com/images/email/message_cards/avatar.png%22,%22action%22:%7B%22name%22:%22Open) in GitHub","url":"[https://github.com/wroscoe/donkey"}},"updates":{"snippets":[{"icon":"PERSON","message":"@easonzrq](https://github.com/wroscoe/donkey%22%7D%7D,%22updates%22:%7B%22snippets%22:%5B%7B%22icon%22:%22PERSON%22,%22message%22:%22@easonzrq) in #308: I have the same question.\r\nHow do you fix it ?can you tell me \r\n3Q"}],"action":{"name":"View Issue","url":"[#308 (comment)](https://github.com/wroscoe/donkey/issues/308#issuecomment-430916478)"}}} [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#308 (comment)](https://github.com/wroscoe/donkey/issues/308#issuecomment-430916478)", "url": "[#308 (comment)](https://github.com/wroscoe/donkey/issues/308#issuecomment-430916478)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } }, { "@type": "MessageCard", "@context": "http://schema.org/extensions", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [wroscoe/donkey] Illegal array length, must be 15 (#308)", "sections": [ { "text": "", "activityTitle": "**easonzrq**", "activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png", "activitySubtitle": "@easonzrq", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n"commandName": "IssueComment",\n"repositoryFullName": "wroscoe/donkey",\n"issueId": 308,\n"IssueComment": "{{IssueComment.value}}"\n}" } ] }, { "targets": [ { "os": "default", "uri": "[#308 (comment)](https://github.com/wroscoe/donkey/issues/308#issuecomment-430916478)" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n"commandName": "MuteNotification",\n"threadId": 375088529\n}" } ], "themeColor": "26292E" } ]
> 
> sorry,i cant find where to change the mode.can you tell me ?

open manage.py
def drive()
......
kl = KerasLinear()[I have changed to KerasCategrocial]
......


def train()
......
kl = KerasLinear()[same to drive]
......
