### ISSUE TITLE
It seems not commit or accept code for almost 2 month.

### ISSUE THREAD

**Issue by whllhw** [autorope/donkeycar#330]
Hi ,@wroscoe thank you for this amazing repo. May be busying on something others, you hadn't got any commit or accept other's code. Is it possible to create a team manage this project ?

**Comment by scitronboy** [comment]
There _are_ currently 22 open PRs, the oldest from August 6

**Comment by wroscoe** [comment]
I'm back on the horse here and have created this team repo. Happy to add people who would like to maintain a part or other repo.
