### ISSUE TITLE
Is the source for donkeycar.com open-source? - Add docs link to donkeycar.com navbar

### ISSUE THREAD

**Issue by scitronboy** [autorope/donkeycar#332]
There really needs to be a link in the navbar at [www.donkeycar.com](http://www.donkeycar.com/) that links to the [donkeycar docs](http://docs.donkeycar.com/). I'd add it myself except I don't know where the source code is for donkeycar.com. This might be a stupid question, but where is it? It's not in donkeycar/gh-pages... I also have quite a few other changes that I think should be made to donkeycar.com so if you could open-source www.donkeycar.com (or let me know where it is!) that would be great @wroscoe . Thanks!

**Comment by wroscoe** [comment]
Done
