### ISSUE TITLE
Discussion: Donkeycar prebuilt zipped disk image

### ISSUE THREAD

**Issue by mancoast** [autorope/donkeycar#348]
Greetings,

Is it possible to build the disk image for RPi 3B and 3B+ for RPi Zero using continuous integration?
Currently these files hosted on google drive, what is the process for building the images from scratch?
Looking forward to our collaboration.

Thanks,
Coast

**Comment by wroscoe** [comment]
I like this idea but it would require some work to build the disk image in a CI environement. donkeycar currently used travis ci. This is the script used to build the image.

https://github.com/autorope/donkeycar/blob/dev/install/pi/install.sh

Then this is the process to actually make the iso file https://github.com/autorope/donkeycar/blob/dev/docs/release.md

**Comment by filips123** [comment]
Maybe you could use [pi-gen](https://github.com/RPi-Distro/pi-gen) for that. It is used for official Raspbian images.

In RPi-Distro/pi-gen#198, they said that it could work in Docker or Travis CI. I didn't tested this yet but maybe this can be used to build image in Travis CI (or other CI).

**Comment by tawnkramer** [comment]
thanks for your input. We will be moving away from pre-built images to a series of install steps/scripts. This is easier to maintain.

**Comment by mancoast** [comment]
@tawnkramer Will these scripts be executed on travis continuous integration?
