### ISSUE TITLE
Changes needed to install instructions to run on a rpi 3b

### ISSUE THREAD

**Issue by mtfurlan** [autorope/donkeycar#358]
I found a few issues trying to get donkeycar running on a pi, following the instructions at
https://docs.donkeycar.com/guide/install_software/#install-donkeycar-on-linux

Originally, I tried the prebuilt, had a few issues with networking, and gave up because I've had a history of having issues with how people package pi images sometimes.

So just following the linux install instructions:
It says
```
sudo apt-get install virtualenv build-essential python3-dev gfortran libhdf5-dev
virtualenv env -p python3
source env/bin/activate
pip install tensorflow==1.8.0
```
If you install tensorflow 1.8.0, that was compiled for python 3.4 and a pi has python 3.5.
You also need to install `libatlas-base-dev libopenjp2-7-dev libtiff5`
Also run
```
pip install picamera Adafruit_PCA9685
```
So put together,
```
sudo apt-get install virtualenv build-essential python3-dev gfortran libhdf5-dev libatlas-base-dev libopenjp2-7-dev libtiff5
virtualenv env -p python3
source env/bin/activate
pip install tensorflow picamera Adafruit_PCA9685
```
At this point, also run raspi-config and enable camera and i2c in the interfacing options, and reboot.

There is then a link to calibrate car, which references `donkey createcar`, but doesn't tell you what it is.

If you skip around to the drive the car page, it says to run
```
donkey createcar --template donkey2 --path ~/mycar
```
Sadly, `donkey createcar` has never heard of this `--path` flag, but if you run it without anything, it says it's missing the path.
```
donkey createcar --template donkey2 ~/mycar
```

I think that's all the changes I had to make to get it to work.

**Comment by tawnkramer** [comment]
thanks! should be fixed now.
