### ISSUE TITLE
NameError: name 'JoystickController' is not defined

### ISSUE THREAD

**Issue by custom-build-robots** [autorope/donkeycar#360]
Hello everyone,
since I installed the latest donkey car version 2.5.8 I am no longer able to use my PS4 controller connected via DualShock 4 USB Wireless Adaptor. In the past I had no problem to use the PS4 controller to steer my Donkey Car.

Below is the error I get since I updated today my Donkey Car. I downloaded the latest image for the Raspberry Pi 3 Model B+ and installed verything as described.

Update 1:
I think the controller.py file is missing? Maybe I missed something or this causes the error...

Update 2:
I copied an old controller.py file in the foler "~/env/lib/python3.5/site-packages/donkeycar/parts"
Changed the manage.py file and added this line:
from donkeycar.parts.controller import JoystickController

NOW MY PS4 CONTROLLER IS WOKING AGAIN...

ERROR MESSAGE:
(env) pi@donkeypi:~/mycar $ python manage.py drive
using donkey version: 2.5.8 ...
/usr/lib/python3/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
loading config file: /home/pi/mycar/config.py
config loaded
PiCamera loaded.. .warming camera
Traceback (most recent call last):
  File "manage.py", line 176, in <module>
    drive(cfg, model_path=args['--model'], use_joystick=args['--js'], use_chaos=args['--chaos'])
  File "manage.py", line 48, in drive
    ctr = JoystickController(max_throttle=cfg.JOYSTICK_MAX_THROTTLE,
NameError: name 'JoystickController' is not defined

This picture shows the donkey car error message I now get:
![donkey_car_joystick_error_message](https://user-images.githubusercontent.com/23113783/49701327-56fb5b80-fbeb-11e8-9703-1d7014e7f290.jpg)

If I start this little python program to test my PS4 controller it works perfct:

#!/usr/bin/env python
import struct
infile_path = "/dev/input/js0"
EVENT_SIZE = struct.calcsize("LhBB")
file = open(infile_path, "rb")
event = file.read(EVENT_SIZE)
while event:
    print(struct.unpack("LhBB", event))
    (tv_msec,  value, type, number) = struct.unpack("LhBB", event)
    event = file.read(EVENT_SIZE)

This picture shows the output of my python joystick test program:
![joystick_py_out](https://user-images.githubusercontent.com/23113783/49701326-56fb5b80-fbeb-11e8-97d4-24365e9a7a1a.jpg)

Thank you very much for your help or ideas

Ingmar

**Comment by ndnparis** [comment]
Hi,
I have the same issues with my PS3 joystick.
It works with other apps but not with donkeycar.
Hope someone could help us.

**Comment by kevkruemp** [comment]
The newest update does appear to be missing the proper controller file. I will see if this can be remedied.

**Comment by vihank** [comment]
> The newest update does appear to be missing the proper controller file. I will see if this can be remedied.

Has this issue been fixed yet?

**Comment by jmonsalve15** [comment]
Hi @custom-build-robots, I am having the same issue but I don’t have the old versions of Donkey repo, can you share the missing file or show me from where could I download? I am pretty new and I getting struggles to found info here. Thanks

**Comment by pitkane** [comment]
As Ingmar said, copying the file `controller.py` from older build kind of solves the problem.

```
cd ~/env/lib/python3.5/site-packages/donkeycar/parts/
wget https://github.com/autorope/donkeycar/blob/2.5.1/donkeycar/parts/controller.py


```

In `manage.py`
```
from donkeycar.parts.controller import JoystickController
```

**Comment by tawnkramer** [comment]
please be on the lookout for donkey 3.0. This will have all the controller support in the main repo.
