### ISSUE TITLE
Hardware PWM control with BCM 18 & 19

### ISSUE THREAD

**Issue by wallarug** [autorope/donkeycar#374]
As per discussions in the donkey car slack #hardware channel between Jesse Cha and the community - it _might_ be possible to control the servo and ESC motors without the need for the PCA9685.

**Example Code** - Provided by Jesse Cha
```
import pigpio
pi = pigpio.pi ()
pi.hardware_PWM(19, 75, 1e6*throttle)
pi.hardware_PWM(18, 75, 1e6*steering) 
```

This would be an enhancement that should be implemented in actuators.py

I'm happy to try and take this on if no one else does before me.

**Comment by tawnkramer** [comment]
this code will be there in donkey 3.0. check donkeycar/parts/actuator.py PiGPIO_PWM
