### ISSUE TITLE
ModuleNotFoundError: No module named 'donkeycar'

### ISSUE THREAD

**Issue by flamedbaby** [autorope/donkeycar#382]
Please see: https://i.imgur.com/vUSTvxs.png

Any advise?

**Comment by Schmill** [comment]
It _looks_ like you haven't installed the donkeycar package within the donkey environment?

**Comment by tawnkramer** [comment]
please follow all steps on:
https://docs.donkeycar.com/guide/install_software/#install-donkeycar-on-windows

if you get an error, please report that.

it looks like the step you missed was:
pip install -e .
This should be done while donkey environment is active ( conda activate donkey ), and you are in the donkey source dir ( ie. projects/donkeycar )
