### ISSUE TITLE
tubclean broken

### ISSUE THREAD

**Issue by Schmill** [autorope/donkeycar#394]
It looks like commit 9da239ce81817689a5428c02614d1df79f838315 removed the "donkeycar" directory, and since that point the tubclean won't work since the various webpages needed for it now longer exist.
I'm happy to do a pull request to reintroduce it, but I wanted to check whether it was _deliberately_ removed first.

**Comment by tawnkramer** [comment]
That was overlooked. You are welcome to add again. Thanks!

**Comment by Schmill** [comment]
Many thanks, expect another pull request shortly :)
