### ISSUE TITLE
doc update: opencv build

### ISSUE THREAD

**Issue by macfly1202** [autorope/donkeycar#397]
There is a little typo in jetson nano setup on the related page http://docs.donkeycar.com/guide/robot_sbc/setup_jetson_nano/

This is for the optional opencv build from source. 

```
# Create a build directory
cd projects/cv2
mkdir build
cd build
```

The right folder is 
```cd projects/cv2/opencv``` and not ```cd projects/cv2```  if we follow instruction carefully.

**Comment by tikurahul** [comment]
You are correct. The right folder is `projects/cv2/opencv`.

**Comment by tawnkramer** [comment]
thanks! docs updated now.
