### ISSUE TITLE
Docs: Should UUID be rootfs or are their other options.

### ISSUE THREAD

**Issue by wroscoe** [autorope/donkeycar#403]
Should the docs read 
```
sudo vi /media/userID/rootfs/etc/hostname
sudo vi /media/userID/rootfs/etc/hosts
```

I've always seen rootfs instead of any UUID

in step three of the install software for raspberry pi https://github.com/autorope/donkeycar/blob/dev/docs/guide/robot_sbc/setup_raspberry_pi.md

**Comment by nvtkaszpir** [comment]
It really depends on udev config on the host, which is later using udiskctl to mount disks.
Current docs use UUID.

I believe this can be closed.
