### ISSUE TITLE
Device Tilt stopped working with iOS 12.3.1

### ISSUE THREAD

**Issue by gernertd** [autorope/donkeycar#413]
My car worked absolutely fine but with the last iPhone update (or the one before) I can't control the car by device tilt anymore. Joystick still works.

**Comment by tawnkramer** [comment]
Web sites can’t access tilt by default anymore. You have to enable it in Safari settings. 

Even with that seems it’s still broken. Any takers on looking into it?

**Comment by tawnkramer** [comment]
the problem is deeper. We can't get tilt events unless we have an SSL connection. Using a self signed cert would result in many warnings for users. Looks like this feature is gone.
