### ISSUE TITLE
User/Local angle mode switching

### ISSUE THREAD

**Issue by kudling** [autorope/donkeycar#425]
Whenever i start the car in Local Angle mode, it switches to User mode after i provide user input from the web interface.
Consider updating the web interface to be stateful, so it won't be switching back to defaults all the time.
I have similar issues with switching recording and the start vehicle button - they do not seem to correspond to actual states.

**Comment by tawnkramer** [comment]
this is a safety measure as it allows you to take control if the car goes off the rails.
