### ISSUE TITLE
Stop Sign Detection

### ISSUE THREAD

**Issue by python1995** [autorope/donkeycar#441]
My donkey car is working quite good. after  training, it is able to go through a path.
I  did that based on this
https://github.com/autorope/donkey2

I want o implement the feature of the car stopping when it sees a stop traffic light .

Can anyone suggest any github projects that could help me with this .

**Comment by tawnkramer** [comment]
please visit donkeycar.com and sign up for our slack channel. That's the best venue for help on new features.
