### ISSUE TITLE
makemovie salient cropping

### ISSUE THREAD

**Issue by ebswift** [autorope/donkeycar#442]
I don't think this is related to #438 because I get the movie to make to completion without errors with salient.  If I train a model with roi_crop set, then makemovie against this model, the salient highlighting displays over the whole frame, it does not skip the cropped area as expected.  The idea would be to train with cropping, then use salient to look at the results.

Discussion here:
https://donkeycar.slack.com/archives/C4HR56WN6/p1564444240093600

**Comment by Schmill** [comment]
Which codebase are you using? (Which version and branch?)

**Comment by ebswift** [comment]
3.02 dev revision 6a613f52

**Comment by tawnkramer** [comment]
should be fixed now in dev. Will try to roll into master soon.
