### ISSUE TITLE
Add GUI or configuration option to flip/rotate the camera

### ISSUE THREAD

**Issue by dmccreary** [autorope/donkeycar#447]
We are using the Nvidia Nano and the new Module V2 camera.  The image comes up upsidedown on the web display.  The only way I could find to flip the image was to go into the DonkeyCar parts, find camera.py file and change line 142 in the CSICamera init:

https://github.com/autorope/donkeycar/blob/dev/donkeycar/parts/camera.py
gstreamer_flip=0
to be:
gstreamer_flip=2

**Comment by adricl** [comment]
You can change the nano cameras rotation by using the line in myconfig.py CSIC_CAM_GSTREAMER_FLIP_PARM= 2
