### ISSUE TITLE
ValueError: dutycycle must have a value from 0.0 to 100.0，when i run the instruction: python ~/mycar/manage.py drive --model ~/mycar/models/mypilot.h5

### ISSUE THREAD

**Issue by jiawenbin2013** [autorope/donkeycar#454]
ValueError: dutycycle must have a value from 0.0 to 100.0，when i run the instruction: python ~/mycar/manage.py drive --model ~/mycar/models/mypilot.h5
<img width="576" alt="WechatIMG601" src="https://user-images.githubusercontent.com/5269568/64141609-51aa0500-ce3b-11e9-91e5-01ee95267d8d.png">

**Comment by tawnkramer** [comment]
this looks like an old install. please try re-installing with latest instructions.

**Comment by jiawenbin2013** [comment]
I have resolve the problem which caused by the version is not same。

**Comment by Xzess** [comment]
I have the same problem like you. But i don't know how to fix it properly. 
How exactly did you solve the problem? Which version did you upgrade/downgrade?

**Comment by MciMoonchester** [comment]
I have resolve it by changing the wrong bit operation
