### ISSUE TITLE
No TARGET_H, TARGET_W, TARGET_D

### ISSUE THREAD

**Issue by coolerking** [autorope/donkeycar#455]
I ran as follows:
python manage.py train --model models/foo.h5

but error occurs in train.py line463

```python
                    img_arr = np.array(inputs_img).reshape(batch_size,\
                        cfg.TARGET_H, cfg.TARGET_W, cfg.TARGET_D)
```

because of no defined parameters(TARGET_H, TARGET_W, TARGET_D.

so I wrote them to myconfig.py (or wrote as follows) and ran again without error.

```python
                    img_arr = np.array(inputs_img).reshape(batch_size,\
                        cfg.IMAGE_H, cfg.IMAGE_W, cfg.IMAGE_DEPTH)
```

**Comment by tawnkramer** [comment]
seems like your setup is out of sync. try re-installing with latest instructions. Also, please include all output when reporting an error, as well as what platform.

**Comment by tawnkramer** [comment]
Please update us if still having this issue with latest.
