### ISSUE TITLE
After training, the car can't recognize the road in the new environment.

### ISSUE THREAD

**Issue by 0102TH** [autorope/donkeycar#484]
At first,I just run the  virtual car by myself and record the  training pictures, via `python manage.py drive`.
And then ,train the datas via `python manage.py train --model ./models/mypilot.h5`.
After trainingthe data,run `python manage.py drive --model ./models/mypilot.h5`  enter one new environment and open the browser,input the ip(including 8883) of my computer,choose the 'Local Pilot(d)',but the car did not run as my wishes.
How can I do it ?
How many training pictures are suitable？
Thank u for your reply.

**Comment by tawnkramer** [comment]
this video may help: https://docs.donkeycar.com/guide/train_autopilot/#training-tips
