### ISSUE TITLE
Raspberry Pi v4b - Doc update request

### ISSUE THREAD

**Issue by shuuse** [autorope/donkeycar#493]
Hi! 
Thanks for great documentation for us noobs. I have a Pi v4 and found that one cannot install Raspbian Stretch on a Raspberry Pi 4b. I would suggest an update in the documentation for Pi v4.
Stretch has been replaced with Buster for Pi V4, and the instructions work well when that is replaced. The download link is 
https://downloads.raspberrypi.org/raspbian_lite_latest

Kind regards, 
Simon

**Comment by nvtkaszpir** [comment]
PRs are welcome.
