### ISSUE TITLE
Can donkeycar drive with trained tub photos?

### ISSUE THREAD

**Issue by RyanC1681** [autorope/donkeycar#511]
Can donkey car drive with trained tub photos by set CAMERA_TYPE = "MOCK" then use tub as input option as below?
i.e. python manage.py drive [--tub=<tub1,tub2,..tubn>] [--model=] ## to import the real tub photo to drive then output pilot/angle', 'pilot/throttle to test if model works.

Thanks,

**Comment by tawnkramer** [comment]
Please see usage at
http://docs.donkeycar.com/guide/simulator/

**Comment by RyanC1681** [comment]
I couldn't get the simulator work, but I original intend is to import the recorded photo from drive to verify if the trained model work as expected.  Where could I find the code to dump the steer and throttle data during drive?  How to get donkey_path.pkl or train localizer? When I set TRAIN_LOCALIZER = True then it shown KEYError:location during train
Thanks,

**Comment by Bleyddyn** [comment]
I'm not sure this is what you mean but there's a tubplot command:

donkey tubplot --help

e.g. donkey tubplot --model=models/Simulator4.h5 --tub=data/20200509_28.tub

**Comment by Ezward** [comment]
This can be done in the DonkeyUI in the [Pilot Arena](https://docs.donkeycar.com/utility/ui/#the-pilot-arena)
