### ISSUE TITLE
Problems with new numpy version

### ISSUE THREAD

**Issue by bohniti** [autorope/donkeycar#527]
Hello together,

As I tried to run or build a new car, I got an error with the new numpy version. I got back to 1.17 and could fix it quick and dirty. More specific it seems there is a problem with the numpy.testing.nosetester. Has anybody experienced the same or could advise on how to fix it more cleanly?

**Comment by nvtkaszpir** [comment]
freeze packages versions in setup.py?
But AFAIR it's rather issue with pandas.

**Comment by tawnkramer** [comment]
@bohniti did that fix things for you?
