### ISSUE TITLE
web broswer show nothing

### ISSUE THREAD

**Issue by xidianzhuxi** [autorope/donkeycar#531]
after i run python3 manage.py drive。shell tell me go to the ip:8887 to control the car。
but i cant connet this web page just like this
![bug](https://user-images.githubusercontent.com/40211659/72676301-bb653b80-3aca-11ea-9a03-cc70c3dd4f4d.png)

**Comment by nvtkaszpir** [comment]
Does it show anything more after `Init ESC`  message in the console?

**Comment by xidianzhuxi** [comment]
nothing show after `Init ESC`

**Comment by nvtkaszpir** [comment]
Then make sure you have followed the procedure in [creating an donkeycar app ](http://docs.donkeycar.com/guide/create_application/) and [calibrating steering](http://docs.donkeycar.com/guide/calibrate/) because it should show something like:
```
...
PWM Throttle created
Adding part PWMSteering.
Adding part PWMThrottle.
Tub does NOT exist. Creating new tub...
New tub created at: /home/pi/mycar/data/tub_2_20-01-19
Adding part TubWriter.
...
...
Starting vehicle at 20 Hz
```
And then it should show web intrface.

**Comment by xidianzhuxi** [comment]
thanks,i fix it .one year ago,i build donkeycar on my own board and modify the actuator.py。i noticed that the new version seems to support imu?how can i use it?

**Comment by xidianzhuxi** [comment]
sorry but a new problem i find that the web page i can not control.no use to press the button in red zone shows below .and i can not click to drag neither
![bug2](https://user-images.githubusercontent.com/40211659/72677268-7bf01c80-3ad5-11ea-8fff-2cd7cb1eedc7.png)

**Comment by nvtkaszpir** [comment]
On the left in `Mode & Pilot` select mode `User`.
On the top left `Control Mode` select `Joystick`.

Then you should be able to use other controls.

Also ensure not to have any special adblockers or noscript addons enabled.

**Comment by xidianzhuxi** [comment]
I can select mode User in `Mode & Pilot` but i can not select `Joystick` on the top left `Control Mode`.
I press the key space and go to see the tub,no image and json file stored.F12 shows 4 js error.
![bug3](https://user-images.githubusercontent.com/40211659/72677739-a8f2fe00-3ada-11ea-86b1-0bd84302f613.png)

**Comment by xidianzhuxi** [comment]
by the way: i run `python3 manage.py drive --js`  all is well

**Comment by CarloHan** [comment]
Hi, I have the same problem with you, the website shows nothing. May I ask how did you solve the problem? Thx!
