### ISSUE TITLE
pep517 installation problems on jetson nano

### ISSUE THREAD

**Issue by fredriksvensson** [autorope/donkeycar#552]
There is an issue with following the installation guide for jetson nano. Just putting the issue here so others who get the same problem can find the solution easier.

The workaround we found was to suppress pep517:
`pip install -e .[nano] --no-use-pep517`

**Comment by radfordwill** [comment]
I had the same issue. I used the exact work around. Jetson nano rev b01 jetpack 4.4 following the docs at donkeycar.com.

**Comment by Ezward** [comment]
Closed as obsolete.
