### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by md-hexdrive** [autorope/donkeycar#565]
In your web documentation at http://docs.donkeycar.com/guide/build_hardware/, the link to the webpage entitled Roll Your Own is broken. The link is to http://docs.donkeycar.com/roll_your_own.md but it the link should instead lead to http://docs.donkeycar.com/roll_your_own/.

Hopefully this helps.

**Comment by krissdap** [comment]
Pull request submitted
https://github.com/autorope/donkeycar/pull/568
