### ISSUE TITLE
Can donkeycar train with 2x cameras at 120FPS?

### ISSUE THREAD

**Issue by RyanC1681** [autorope/donkeycar#566]
Anyone tried LI-IMX219-MIPI-FF-NANO camera to get 120FPS? Is there benefit to train with 2x CSI stereo cameras at 120FPS? 
   However I tried tub manage that didn’t work with camera_a and _b and python crashed if I increased frame rate > 60.
Thanks

**Comment by tawnkramer** [comment]
Please use discord for this
