### ISSUE TITLE
Same as closed Issue #279 "running manage.py drive get ImportError "No module named 'controller'" #279"

### ISSUE THREAD

**Issue by geminio-john** [autorope/donkeycar#569]
I'm hitting the same problem described in closed issue #279.

I've followed all the steps suggested in the original issue. 

I have re-run the complete installation with the same result . 

git branch -a  shows master in green with an asterisk. However it also shows a line with remotes/origin/HEAD -> origin/dev    This looks a bit suspicious?

Many thanks for any help.

**Comment by tawnkramer** [comment]
You have given no details which would help anyone troubleshoot. Please follow steps in docs.
