### ISSUE TITLE
can't browser the website with "raspberrypi.local:8887"

### ISSUE THREAD

**Issue by CarloHan** [autorope/donkeycar#594]
After running
`python manage.py drive`
I got these:
```(env) pi@raspberrypi:~ $ cd ~/mycar
(env) pi@raspberrypi:~/mycar $ python manage.py drive
using donkey v3.1.2 ...
loading config file: /home/pi/mycar/config.py
myconfig myconfig.py
loading personal config over-rides from myconfig.py

config loaded
cfg.CAMERA_TYPE PICAM
PiCamera loaded.. .warming camera
Adding part PiCamera.
Starting Donkey Server...... you can now go to raspberrypi.local:8887 to drive your car.
Adding part LocalWebController.
Adding part ThrottleFilter.
Adding part PilotCondition.
Adding part RecordTracker.
Adding part ImgPreProcess.
Adding part DriveMode.
Adding part AiLaunch.
Adding part AiRunCondition.
PWM Steering created
Init ESC
PWM Throttle created
Adding part PWMSteering.
Adding part PWMThrottle.
Tub does NOT exist. Creating new tub...
New tub created at: /home/pi/mycar/data/tub_4_20-06-10
Adding part TubWriter.
You can now go to <your hostname.local>:8887 to drive your car.
Starting vehicle at 20 Hz
/usr/lib/python3/dist-packages/picamera/encoders.py:544: PiCameraResolutionRounded: frame size rounded up from 160x120 to 160x128
  width, height, fwidth, fheight)))
```
I'm not sure if it's good or not, but I can't open the website with "raspberrypi.local:8887", or "IP:8887"
hope someone could help me, thank you so much!

**Comment by krissdap** [comment]
The "raspberrypi.local" might work or not depends on your LAN settings.

But the other address shouldn't be "IP:8887". 
"IP" part should be set of four numbers, separated by dot.
E.g. 192.168.1.100.

You could get the IP address by typing "ifconfig -a"
![image](https://user-images.githubusercontent.com/5546755/87165131-eb5fff80-c2f3-11ea-98fb-ebdcb17ce695.png)
So for example, in this case we should use "http://192.168.1.128:8887"

**Comment by krissdap** [comment]
And your other question, I don't think the SSH is frozen.
But the python script is running.
You could try pressing "Ctrl-C" on your keyboard, to see if it terminates the script.

**Comment by DocGarbanzo** [comment]
@CarloHan - can you let us know if you solve the issue?

**Comment by DocGarbanzo** [comment]
Closed due to inactivity.

**Comment by co2131** [comment]
Hi we try https://10.18.217.170:8887 on our web browser and the page is also not working. Does anyone know how to get access to the web control?
