### ISSUE TITLE
does it work on raspberry pi 2?

### ISSUE THREAD

**Issue by manjeetbhatia** [autorope/donkeycar#600]
would this project work on raspberry pi2 ? does it need inbuilt wifi module?
I'm planning to setup rapsberry pi using ethernet cable.

**Comment by tawnkramer** [comment]
There’s no support for pi2 at this time.

**Comment by Hackerman342** [comment]
Also curious about pi 4b? Or should I just get 3b+ like the docs suggest?

**Comment by tawnkramer** [comment]
3b+ easier when starting out. Fewer power issues. Pi4 has been tested. No
to pi4b.

**Comment by manjeetbhatia** [comment]
do you mean no issues with 4b? I'm planning to get this https://www.amazon.com/Raspberry-Model-2019-Quad-Bluetooth/dp/B07TD42S27/ref=sr_1_3?dchild=1&keywords=raspberry+pi+4&qid=1593042158&sr=8-3 . Thanks

**Comment by tawnkramer** [comment]
I didn’t say no issues. I said No to 4b.

**Comment by manjeetbhatia** [comment]
ok, thanks I'll get 3b+
