### ISSUE TITLE
Move away from DRIVE_TRAIN_TYPE and HAVE_

### ISSUE THREAD

**Issue by wallarug** [autorope/donkeycar#615]
Can we please pick one standard?   

Having both is causing some issues for people as it is counterproductive to have to turn something on twice.

My recommendation would be to use only two variables throughout and remove all the `HAVE_BOARD` ones.

`CONTROLLER_TYPE=""`
 `DRIVE_TRAIN_TYPE=""`

**Comment by tawnkramer** [comment]
the have sombrero doesn't change the drive train type

**Comment by DocGarbanzo** [comment]
@wallarug - is this still an active problem?

**Comment by zlite** [comment]
Yes, this is still suboptimal. I agree with @wallarug that we should define inputs (controller type) and outputs (drive trains) and that no other board definition should be required. In this case "HAVE_ROBOHAT" is redundant and should be removed in the code and replaced with either "controller_type" or "drive_train_type" as appropriate

**Comment by zlite** [comment]
Fixed with this PR: https://github.com/autorope/donkeycar/pull/851
