### ISSUE TITLE
The latest version of Jetpack (4.4) comes with TensorRT preinstalled

### ISSUE THREAD

**Issue by TCIII** [autorope/donkeycar#626]
Presently the DC docs for using TensorRT on the Jetson Nano, for the purpose of training, require the installation of TensorRT, cuDNN and CUDA on the Nano.
This step (Step 1: Setup TensorRT on Ubuntu Machine) is no longer required as Jetpack 4.4 has TensorRT 7.1.3, cuDNN 8.0 and CUDA 10.2 preinstalled.
Recommend stating that if the user has installed Jetpack 4.4 (latest version) on their DC Nano, they can skip to Step 2: Setup TensorRT on your Jetson Nano.

**Comment by Ezward** [comment]
Closing as obsolete.
