### ISSUE TITLE
Failed to load the native TensorFlow runtime

### ISSUE THREAD

**Issue by MrRivi** [autorope/donkeycar#627]
Hi, has anyone run into these two linked errors?

1. Failed to load the native TensorFlow runtime
2. ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

Thanks in advance :)

![Image1](https://user-images.githubusercontent.com/65244140/92412491-5d19c580-f14c-11ea-9f60-8b63a5340b37.png)
![Image2](https://user-images.githubusercontent.com/65244140/92412493-5db25c00-f14c-11ea-9b15-5ab94397d9e6.png)

**Comment by TCIII** [comment]
@MrRivi,
I assume that you have transferred your tub data and are doing the training on your PC (conda) as your Rpi can't hack it or you are attempting to train on your Nano and that requires setting up TensorRT on the Nano since it comes preinstalled with Jetpack 4.4?

**Comment by MrRivi** [comment]
Correct, I am using a Raspberry pi 4B 4Gb. Following the tutorial at the donkey webpage I transferred the tub data to my PC to train the autopilot model. I am working with Ubuntu 18 on a VirtualBox but I think that shouldn't be an issue.

I also did the "Optional Install Tensorflow GPU - only for NVidia Graphics cards".

I haven't tried to train the model on the Rpi, I've read it could take a lot of time.

**Comment by tawnkramer** [comment]
Don’t think the gpu cuda driver will work in a VM. Search on that and see
if I’m wrong. But try native windows install and you’ll be fine for cuda
drivers.

**Comment by TCIII** [comment]
@MrRivi,
I am running conda on my HP I7 laptop with Windows 10 and haven't had a problem. As tawn said above, doing a native windows install might be better.

**Comment by MrRivi** [comment]
Trying it out right now as you said, on my Dell with Windows 10. I followed the instructions for Win10 on the donkey website and no problems so far :)

The Anaconda Prompt stopped (image below) and threw out this graph. Thank you for the help!!

![Figure 1](https://user-images.githubusercontent.com/65244140/92444800-b0732e80-f1b3-11ea-9860-66defdaf65cd.png)
![Figure 2](https://user-images.githubusercontent.com/65244140/92444803-b10bc500-f1b3-11ea-8b7c-221e57db6f30.png)
