### ISSUE TITLE
Issue with loading from drive.py with Python3.6 (windows)

### ISSUE THREAD

**Issue by wallarug** [autorope/donkeycar#654]
The script refuses to run unless I make the below changes to drive.py.  It appears that the argument parser is looking at the Usage line for the format.  Since `myconfig` is missing from it, it refuses to launch because it doesn't understand when the user gives it the --myconfig argument. 

**Current:**
```
Usage:
    manage.py (drive) [--model=<model>] [--js] [--type=(linear|categorical)] [--camera=(single|stereo)] [--meta=<key:value> ...]

```

**Fix:**
```
Usage:
    manage.py (drive) [--model=<model>] [--js] [--type=(linear|categorical)] [--camera=(single|stereo)] [--meta=<key:value> ...] [--myconfig=<filename>]
```

**Comment by tikurahul** [comment]
This is also fixed by https://github.com/autorope/donkeycar/pull/656
