### ISSUE TITLE
Simulator template minor error

### ISSUE THREAD

**Issue by Keenan1967** [autorope/donkeycar#671]
https://github.com/autorope/donkeycar/blob/f162c76ee222f000f7fb024003da896f5ead623c/donkeycar/templates/simulator.py#L337

In the above line, I think it should instead be:
return pilot_angle if pilot_angle else 0.0, pilot_throttle * cfg.AI_THROTTLE_MULT if pilot_throttle else 0.0, pilot_brake if pilot_brake else 0.0

Without the safety check for pilot_throttle, my program was crashing when trying to run an AI

**Comment by sctse999** [comment]
@wallarug can you check?

**Comment by wallarug** [comment]
Resolved in PR #672

**Comment by wallarug** [comment]
This issue can be closed when someone with closing privileges passes through next.  @Keenan1967

**Comment by Keenan1967** [comment]
Line has been fifxed now
