### ISSUE TITLE
Error when running "python manage.py drive

### ISSUE THREAD

**Issue by StetsonThompson** [autorope/donkeycar#678]
When running python manage.py drive, i get this 

pi@aicar1:~/mycar $ cd
pi@aicar1:~ $ cd ~/mycar
pi@aicar1:~/mycar $ python manage.py drive
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    from docopt import docopt
ImportError: No module named docopt
pi@aicar1:~/mycar $

**Comment by adricl** [comment]
It looks like you have not activated your virtual env did you follow these instructions http://docs.donkeycar.com/guide/robot_sbc/setup_raspberry_pi/?

**Comment by DocGarbanzo** [comment]
Closed due to inactivity.
