### ISSUE TITLE
myconfig.py missing AI_THROTTLE_MULT parameter

### ISSUE THREAD

**Issue by custom-build-robots** [autorope/donkeycar#736]
After installing (2021.01.11) the latest donkey car version the parameter AI_THROTTLE_MULT was missing in the myconfig.py.
The simulator always chrashed with an error as shown in the picture.
Not sure if this is a problem of the gym donkey car framework I had to install or of the official release.
![new_mode_local_error](https://user-images.githubusercontent.com/23113783/104269193-f90a6380-5495-11eb-85ed-effdf4048ace.png)

**Comment by DocGarbanzo** [comment]
Addressed int #747.
