### ISSUE TITLE
Show histogram is missing in 4.x

### ISSUE THREAD

**Issue by sctse999** [autorope/donkeycar#754]
Back in the days of 3.x, we are able to use ```donkey tubhist``` to produce a histogram regarding one or multiple tub. 4.x doesn't have this yet.

In the mobile app, we show this to the user to let them understand the distribution of the data they have collected.

![1_jbrfabKiykMsR0G-5rD7eQ (1)](https://user-images.githubusercontent.com/6903470/105026875-07eea880-5a8a-11eb-90ec-a9676667ae8b.png)

https://github.com/autorope/donkeycar/blob/3.1.0/donkeycar/management/base.py#L276

**Comment by DocGarbanzo** [comment]
Fixed in #958
