### ISSUE TITLE
Missing manifest.json file?

### ISSUE THREAD

**Issue by kl2301** [autorope/donkeycar#761]
I am using the Ubuntu application and I have followed the instructions on the Donkeycar documentation for Host PC setup (Linux OS) and the Train an autopilot instructions up to training a model. When I try to execute `donkey train --tub ./data/tub_9_21_01-08 --model ./models/mypilot.h5`, this error is returned.

![image](https://user-images.githubusercontent.com/77814884/105428769-2d97c100-5bf4-11eb-8233-02c8ba2bbd5f.png)

**Comment by kl2301** [comment]
Fixed, I needed to update the tub directory by using the script I found in `~/projects/donkeycar/scripts/convert_to_tub_v2.py`.

**Comment by nonegom** [comment]
> Fixed, I needed to update the tub directory by using the script I found in `~/projects/donkeycar/scripts/convert_to_tub_v2.py`.


May I know how you solved it? about code

**Comment by czj942650673** [comment]
how can i find the manifest.json
