### ISSUE TITLE
Mismatching versions?

### ISSUE THREAD

**Issue by kl2301** [autorope/donkeycar#767]
I'm using the donkeycar docs at docs.donkeycar.com and I am trying to run the command `python manage.py drive --model ~/mycar/models/mypilot.h5` However, I am running into the following error.
![image](https://user-images.githubusercontent.com/77814884/105758479-66d17900-5ef3-11eb-8354-134b86c11aa9.png)
![image](https://user-images.githubusercontent.com/77814884/105758501-6df88700-5ef3-11eb-800e-2308da1bdfea.png)

I'm not sure where this is going wrong, but something I have noticed is that whenever I am ssh'd into my pi, the software says it is using the donkey version 3.1.5. When I am using my Host PC terminal, the software says it is using donkey version 4.1.0. Could this be related? How would I get them to be the same version?

**Comment by tikurahul** [comment]
You are most definitively using the wrong version of Tensorflow.

**Comment by DocGarbanzo** [comment]
Please pull from git and you should be on the latest on both platforms.
