### ISSUE TITLE
Suggestion: convert Keras/Tflite to be multi-threaded on inference

### ISSUE THREAD

**Issue by cloud-rocket** [autorope/donkeycar#770]
We are not utilizing multi-core capability to run the most CPU consuming task and as a result getting low FPS. (See stats here https://github.com/autorope/donkeycar/issues/690). 

I barely measure 19hz on Nano with tflite - based on the resulting calculation (52ms avg for tflite step) FPS cannot be higher (1000 / 52 = 19).

I suggest the following:
* Push `run_threaded` inputs to ordered queue "A" (ordered based on push timestamp)
* Pop from ordered queue B on `run_threaded` output to return the result (block if empty)
* Run Keras/tflite inside `update` while reading inputs from queue "A" and pushing outputs to queue "B" (based on the same input timestamp order)

As a result get almost x4 FPS on Pi4 or almost x8 FPS on Nano!!!!

What do you think? I can push the code, but I don't have any working environment (my models are not yet working) - so I need somebody to test it in a real environment.

/cc: @DocGarbanzo , @sctse999, @tikurahul

**Comment by DocGarbanzo** [comment]
I get full CPU utilisation when running inference on RPi, because `numpy` and probably `tf` too are using multithreading internally.

**Comment by tikurahul** [comment]
I get > 45 Hz easily. I am not sure where the bottlenecks are in your case.

**Comment by cloud-rocket** [comment]
> I get > 45 Hz easily. I am not sure where the bottlenecks are in your case.

What is your setup?

**Comment by tikurahul** [comment]
I use a Jetson Nano, so my experience may not be super applicable here. :smile:

**Comment by DocGarbanzo** [comment]
Actually after a recent RPi software upgrade, tf has become much slower for '.h5' models, that's probably the reason why you are seeing this. Do you see the same affect also for `.tflite` models?

**Comment by cloud-rocket** [comment]
I am working on a generic multi-threaded solution (please see -https://github.com/cloud-rocket/donkeycar/blob/add-multithreaded-keras-pilot/donkeycar/parts/keras.py)

But for some reason I only experience performance degradation (on both h5 and tflite options) - still not yet understand why...

**Comment by DocGarbanzo** [comment]
Can you check with the latest version on dev. Set the variable `CREATE_TENSOR_RT = True` and use the `.trt` tensorrt model on the nano?

**Comment by Ezward** [comment]
I'm going to close this.  Both Tensorflow and Tensorflow Lite support multi-threaded inference.  Here is Google's page on how to profile a model and the levers for increasing performance, including throwing more threads at it.  https://www.tensorflow.org/lite/performance/best_practices#tweak_the_number_of_threads
