### ISSUE TITLE
How to add another new Throttle to Donkey Car?

### ISSUE THREAD

**Issue by Choikyungho9** [autorope/donkeycar#789]
Hi. I want to add a new throttle to the donkey car code.

When referring to the throttle code in config.py and adding the code to a variable called throttle_2, donkey calibrate works in channel 2, but does not work in donkey drive. (I am controlling the drive with the joystick now.)

How to create an extra throttle?
I want to add throttle_2 to train donkey car.
Do you have a guide on this?

**Comment by DocGarbanzo** [comment]
If you want to use a different variable, you need to set up a part that uses it (i.e. writes to it or reads to it). Tawn has made a great video about donkeycar parts, pls check out https://youtu.be/YZ4ESrtfShs.
