### ISSUE TITLE
Steering and Throttle issue i2c

### ISSUE THREAD

**Issue by BossZweifel** [autorope/donkeycar#795]
Hi there,

I am using a raspberry pi 4 with the waveshare racer kit. My raspberry detects the following i2c addresses

![image](https://user-images.githubusercontent.com/20640022/109391491-a555bb80-7917-11eb-8abd-a282d4488cd4.png)

As standard, 0x40 is used for steering, and 0x60 for throttle. As you can see, I don't have a 0x60 i2c address detected. 

If I put both on 0x40, my web interface shows everything correctly but does not let me control the car. If I change the throttle to any other available address, my steering seems to work but my throttle does nothing. 

While calibrating, the servo and motor were fully functional. This leads me to believe there is a problem with the i2c configuration.

Screenshots from config.py

![image](https://user-images.githubusercontent.com/20640022/109391578-15fcd800-7918-11eb-899b-1016d97cf34c.png)

![image](https://user-images.githubusercontent.com/20640022/109391584-1c8b4f80-7918-11eb-9683-06c4546d531a.png)

Does anybody have a solution for this? 
Thanks in advance!

**Comment by TCIII** [comment]
@BossZweifel

First off "PCA9685_I2C_BUSNUM =" should be set to "None" for the Rpi.
Second, I doubt that the DC software is setup to work with two PCA9685s (such as ADDR1) at the same address.
You might want to pose your issue [here](https://discord.com/channels/662098530411741184/671604048218292233).

**Comment by zlite** [comment]
Yes, I think you can use two devices with the same I2C address as long as they're on different buses, which are determined by which pins you connect them to on the Pi or Nano. (I2C1 and I2C2)

**Comment by BossZweifel** [comment]
Updating to donkey v4.x helped in my case. I can now steer and throttle in the web interface. Seems like the old version is bugged. 
Thanks for your help
