### ISSUE TITLE
Tensorflow training error: AttributeError: module 'tensorflow.compat.v2' has no attribute '__internal__'

### ISSUE THREAD

**Issue by aniruddha2007** [autorope/donkeycar#816]
i have tried on Ubuntu, windows, windows WSL
also tried different tensorflow versions from 2.1.0-2.4.1
![Anaconda Prompt (miniconda3) 18-03-2021 15_26_41](https://user-images.githubusercontent.com/66187064/111588331-5efcc980-87fe-11eb-86fc-8e7c567e3328.png)
please suggest a solution couldn't find a similar issue raised.
Hardware Info:
CPU intel i5 7400
GPU Nvidia 1080 using cuda toolkit 11.0(also tried using 10.2)

**Comment by DocGarbanzo** [comment]
You need to install TF 2.2.0. There is a new section in the docs how to do this on windows: https://docs.donkeycar.com/guide/host_pc/setup_windows.html - can you check your error disappears with that?

**Comment by DocGarbanzo** [comment]
Closed due to inactivity.
