### ISSUE TITLE
tensorflow 2.3.0 performance issue on rpi4 in donkey 4.x

### ISSUE THREAD

**Issue by JoeyZhu** [autorope/donkeycar#827]
I noticed KerasLinear used unsual longger time in donkey 4.x then donkey 3.x:
Part Profile Summary: (times in ms)
+---------------------------+--------+--------+--------+--------+--------+--------+--------+
|            part           |  max   |  min   |  avg   |  50%   |  90%   |  99%   | 99.9%  |
+---------------------------+--------+--------+--------+--------+--------+--------+--------+
|          PiCamera         |  0.09  |  0.03  |  0.03  |  0.03  |  0.04  |  0.05  |  0.09  |
| XboxOneJoystickController |  0.24  |  0.04  |  0.05  |  0.05  |  0.06  |  0.07  |  0.18  |
|       ThrottleFilter      |  0.08  |  0.02  |  0.03  |  0.03  |  0.03  |  0.04  |  0.07  |
|       PilotCondition      |  0.11  |  0.02  |  0.02  |  0.02  |  0.02  |  0.03  |  0.09  |
|       RecordTracker       |  0.04  |  0.02  |  0.02  |  0.02  |  0.02  |  0.03  |  0.04  |
|        FileWatcher        |  1.04  |  0.07  |  0.12  |  0.08  |  0.28  |  0.41  |  0.98  |
|        FileWatcher        |  0.66  |  0.05  |  0.07  |  0.06  |  0.06  |  0.44  |  0.64  |
|       DelayedTrigger      |  0.06  |  0.02  |  0.02  |  0.02  |  0.03  |  0.04  |  0.06  |
|     TriggeredCallback     |  0.02  |  0.02  |  0.02  |  0.02  |  0.02  |  0.02  |  0.02  |
|        KerasLinear        | 566.66 | 285.50 | 303.88 | 295.06 | 318.53 | 416.84 | 551.68 |
|         DriveMode         |  0.30  |  0.03  |  0.05  |  0.03  |  0.16  |  0.21  |  0.27  |
|          AiLaunch         |  0.07  |  0.02  |  0.03  |  0.03  |  0.04  |  0.04  |  0.06  |
|       AiRunCondition      |  0.07  |  0.02  |  0.02  |  0.02  |  0.02  |  0.03  |  0.06  |
|        PWMSteering        |  0.18  |  0.04  |  0.05  |  0.04  |  0.12  |  0.13  |  0.17  |
|        PWMThrottle        |  0.13  |  0.03  |  0.04  |  0.03  |  0.05  |  0.06  |  0.11  |
+---------------------------+--------+--------+--------+--------+--------+--------+--------+

I tried to install tf 2.2.0, but it is same slow. Have anyone have the same issue?

**Comment by qasimalik134** [comment]
@JoeyZhu I have encountered similar issue. However, it was fixed by reinstall all packages.

**Comment by DocGarbanzo** [comment]
Please run the tflite model. The linear tflite model in standard resolution gives > 50fps on RPi with cpu cooling (ie avoiding throttling). In h5 version you should get around 8 fps.

**Comment by DocGarbanzo** [comment]
There is now also a fix in `dev` if you want to use the h5 model.
