### ISSUE TITLE
Intel T265 camera will not enumerate correctly on Nano boot up or reboot

### ISSUE THREAD

**Issue by TCIII** [autorope/donkeycar#839]
Hardware: NVIDIA Nano 4 GB
OS: Jetpack 4.5.1
Donkey Car: 4.1.0
Intel RealSense2 SDK: 2.44
T265 camera firmware: 0.2.0.951

Issue:
Due to a quirk in the Nano boot up or reboot process the power to the USB ports appears after the USB controller has received power. This results in the Intel T265 tracking camera not being enumerated correctly by the USB controller during boot up or a reboot.

This enumeration failure issue also results in the failure of the robot car to start without error when running "manage.py drive"  when using a mycar configuration created using the DC "path_follow" template.

Solution:

Need to install [uhubctl](https://github.com/mvp/uhubctl) if you have not already done so.

Then before booting up, plug the T265 USB cable end into the USB port on the bottom next to the HDMI port. That is USB port 2.

After boot up go to /usr/sbin and run "sudo uhubctl -l 1-2 -p 1 -a cycle"

If you then run "sudo uhubctl" it will still show that the T265 is not connected to Hub 2-1 port 2, however if you go to /usr/local/bin and run "rs-enumerate-devices" the T265 camera will be detected.

Now "manage.py drive" will execute without errors in relation to the T265 tracking camera.

These instructions originated from [here](https://github.com/IntelRealSense/librealsense/issues/4681).

**Comment by Ezward** [comment]
We do not have any docs on cameras and we have removed documentation on the T265 since it is no longer supported by Intel and we really never got it working that well.  So I am going to close this.
