### ISSUE TITLE
Sample DataSet is not supported by latest version of donkey car

### ISSUE THREAD

**Issue by qasimalik134** [autorope/donkeycar#844]
Sample DataSet is not supported by latest version of donkey car

**Comment by DocGarbanzo** [comment]
Can you please add which data set you are referring to?

**Comment by DocGarbanzo** [comment]
Actually we create a new repo (https://github.com/autorope/donkey_datasets) and updated the docs accordingly.

**Comment by DocGarbanzo** [comment]
Solved. Pls use https://github.com/autorope/donkey_datasets.
