### ISSUE TITLE
ValueError: The `target` has to be an integer tensor.

### ISSUE THREAD

**Issue by NevGithub0823** [autorope/donkeycar#846]
[Full output https://pastebin.com/mc99v61d](https://pastebin.com/mc99v61d)
I tried training with tensorflow, and it worked fine, I got a model, and it could drive. The error is after I tried to train with pytorch:
```donkey train --tub ./data/data-4-13-2021,./data/data-4-13-2021-1/,./data/data-4-9-2021/ --model ./models/mypilot-pytorch.h5 --framework pytorch --type resnet18```
* OS: I've tried both on Ubuntu 20.04 using Windows 10 multipass and on Windows 10 Anaconda Powershell Prompt
* Python version: 3.7.10
* Pytorch version: 1.7.1
* conda version: 4.9.2
* donkey version: 4.1.0

**Comment by DocGarbanzo** [comment]
@NevGithub0823 - thanks for reporting this. This is a known issue and has been resolved in #830.
