### ISSUE TITLE
python3 manage.py drive has no response

### ISSUE THREAD

**Issue by YoYoHC** [autorope/donkeycar#859]
cant drive the car 
System prompt  

using donkey v4.2.0 ...
Usage:
    manage.py drive [--model=<model>] [--type=(linear|categorical|tflite_linear)]

What shall I do?

**Comment by DocGarbanzo** [comment]
Please post the full shell output of your command and the return.

**Comment by YoYoHC** [comment]
> Please post the full shell output of your command and the return.

(env) pi@raspberrypi:~ $ cd mycar
(env) pi@raspberrypi:~/mycar $ python3 manage.py driver
________             ______                   _________              
___  __ \_______________  /___________  __    __  ____/_____ ________
__  / / /  __ \_  __ \_  //_/  _ \_  / / /    _  /    _  __ `/_  ___/
_  /_/ // /_/ /  / / /  ,<  /  __/  /_/ /     / /___  / /_/ /_  /    
/_____/ \____//_/ /_//_/|_| \___/_\__, /      \____/  \__,_/ /_/     
                                 /____/                              

using donkey v4.2.0 ...
Usage:
    manage.py drive [--model=<model>] [--type=(linear|categorical|tflite_linear)]
(env) pi@raspberrypi:~/mycar $

**Comment by DocGarbanzo** [comment]
Please use `python3 manage.py drive`
