### ISSUE TITLE
Problem with training model on Donkey Car simulator

### ISSUE THREAD

**Issue by OumarDiop** [autorope/donkeycar#863]
When training the model for the virtual donkey car, I get  the error `problems with loss graph: [Errno 2] No such file or directory: 'C:\\Users\\coolDawg1234\\Desktop\\donke\\projects\\donkeycar\\OumarCar\\models\\models\\example_model.png'` Has anyone had this problem or knows a solution? I followed this [guide,](https://docs.donkeycar.com/guide/simulator/) on Windows 10.

**Comment by NevGithub0823** [comment]
from my understanding, in 4.2, they changed it so you have to give the path that's relative to `mycar/models`. so you should change `--model models/example_model.h5` to `--model example_model.h5`. it worked for me.

**Comment by OumarDiop** [comment]
Oh yeah I see that it says `models\\models`, I should've noticed that. I'll try it right now, thanks.

**Comment by DocGarbanzo** [comment]
This has accidentally sneaked into 4.2, we have PR #873 to re-instate the old behaviour. The docs are reflecting what we have in master now. I'll close this, please re-open if you see still an issue.
