### ISSUE TITLE
Donkey Sim "Not Responding"

### ISSUE THREAD

**Issue by NevGithub0823** [autorope/donkeycar#870]
Windows 10.
Donkey Sim works fine, but when I click the "Quit" button, it freezes and shows "Not Responding". Please help.

**Comment by Maximellerbach** [comment]
Hi ! What version of the sim are you using ?
Just checked v21.04.15 and it works fine.

In order to close the app, you can also close just like a regular app using the top right close button of the window: 
![image](https://user-images.githubusercontent.com/38923282/119335013-0f1e0100-bc8c-11eb-92f8-6e2da9b4ffd4.png)

**Comment by NevGithub0823** [comment]
I reinstalled the sim, and now the output says there's a
```
ValueError: Scene name mountain_track not in scene list ['generated_road', 'warehouse', 'sparkfun_avc', 'generated_track', 'roboracingleague_1', 'waveshare', 'mini_monaco', 'warren', 'thunderhill']
```
and
```
RuntimeError: cannot join current thread
```
The Quit button works before the Errors (1-2 seconds after the window opens, the error comes and the Quit button causes Not Responding).

**Comment by NevGithub0823** [comment]
I am also using that version of donkey sim.

**Comment by Maximellerbach** [comment]
Please chose a scene from that list, mountain_track isn't in this version of the sim, that's why it's throwing you an error. For the "Not responding" part, I will take a look at it

**Comment by NevGithub0823** [comment]
> Please chose a scene from that list
I didn't choose mountain_track, it just says I did, idk why

**Comment by Maximellerbach** [comment]
It's in your config file, you should find a variable named "GYM_ENV" or something like that, you need to change it to a valid track name

**Comment by NevGithub0823** [comment]
please tell me which one? 
![image](https://user-images.githubusercontent.com/68718784/119929881-3813ef80-bf33-11eb-8c97-99807042b4ed.png)

**Comment by Maximellerbach** [comment]
There is a list of env name in there, please choose any from it, for example: "donkey-generated-track-v0"
________________________________

**Comment by NevGithub0823** [comment]
thanks, it fixed that error but the window is still not responding after I press quit.
also, "X" button also makes it do that... the only thing that works for me now is to force quit the app or to just ^C in powershell.

**Comment by Maximellerbach** [comment]
Do you disconnect the client before closing the sim ?

**Comment by Maximellerbach** [comment]
Try to close the script and then close the sim, not the other way around

**Comment by Maximellerbach** [comment]
Please tell me if that worked, if it works, let's close this issue

**Comment by NevGithub0823** [comment]
it works
