### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ddwy** [autorope/donkeycar#890]
hello,When I run the command, the following error occurred:

(env) ubuntu@Turtlebot3-virtual-machine:~/d3$ python manage.py drive --model ~/d3/models/mypilot
Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    import donkeycar as dk
  File "/home/ubuntu/donkeycar/donkeycar/__init__.py", line 10
    print(f'using donkey v{__version__} ...')
                                           ^
SyntaxError: invalid syntax

**Comment by DocGarbanzo** [comment]
Which platform are you using? Nano or RPi? Seems your donkey install did not work properly.
