### ISSUE TITLE
„Next, create your Donkeycar application“ results in „404  Page not found“

### ISSUE THREAD

**Issue by Heavy02011** [autorope/donkeycar#891]
On page https://docs.donkeycar.com/guide/robot_sbc/setup_jetson_nano.html clicking on „create your application“ results into „404  Page not found“

**Comment by zlite** [comment]
Now fixed
https://github.com/autorope/donkeydocs/commit/52460a903d8d9a90dda1ed7f4150b0e3dd4f73ad
