### ISSUE TITLE
Version numbers out of sync on Dev branch

### ISSUE THREAD

**Issue by cfox570** [autorope/donkeycar#901]
File at root: setup.py contains "version='4.2.0'"
File at donkeycar: __init__.py contains "__version__ = '4.3.0' " 

Is there a way to only have one place where version is updated?  
In a separate version file?

**Comment by DocGarbanzo** [comment]
Thanks for reporting this. Created #902 to address this.

**Comment by DocGarbanzo** [comment]
This is now merged.
