### ISSUE TITLE
Autopilot ImportError: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by AntonioCervantes** [autorope/donkeycar#908]
Hello, I'm using DonkeyCar 4.2.1 with a Jetson Nano 4GB and got an Import error when trying to run the autopilot using this command: `python manage.py drive --model=models/pilot_21-07-23_0.h5` 
Has anyone else ran into this issue?

I got this error: `ImportError: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block`

![image](https://user-images.githubusercontent.com/87390731/126842806-685035e4-4918-435c-8aa1-3157b6c26c81.png)

![image](https://user-images.githubusercontent.com/87390731/126842607-c9cf0983-5632-4754-9048-23795e9183b8.png)

**Comment by fengye** [comment]
This can workaround it. I think there was a link on the donkeycar docs page but can't find it now but here you go: https://github.com/keras-team/keras-tuner/issues/317#issuecomment-640181692

**Comment by DocGarbanzo** [comment]
@AntonioCervantes - did @fengye's reply solve the issue for you?

**Comment by AntonioCervantes** [comment]
Yes, thank you @fengye and @DocGarbanzo I was able to resolve the issue by typing the following command into the Jetson Nano's terminal:
`export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1`
