### ISSUE TITLE
Tubplot Template Command Throws Error

### ISSUE THREAD

**Issue by flynn248** [autorope/donkeycar#911]
There is a minor issue in the template command shown in the Plot Prediction section of the donkeycar documentation.

The template command shown there is missing the --tub portion behind <tub_path>. Declaring the <tub_path> doesn't work without it.

Also, the last bullet point mentions that the --tub can be omitted. If that also includes the <tub_path>, then a type error occurs when both the --tub and <tub_path> are omitted.

If the last bullet point is meant to only refer to the --tub argument, then the following error appears:
    tubtubplot: error: unrecognized arguments: .\data\

Everything appears to work fine when including the --tub <tub_path> in the command.

Here is the link to the area in the documentation that this appears, https://docs.donkeycar.com/utility/donkey/#clean-data-in-tub(edited)
Link to Discord where it was originally posted: https://discord.com/channels/662098530411741184/671604287419187200/871878663572955136

![image](https://user-images.githubusercontent.com/76095688/128102982-2e574328-06c7-4dff-963c-1d856d40acc2.png)

**Comment by DocGarbanzo** [comment]
@flynn248 - thanks for identifying this error. You can also do a PR directly to `donkeydocs` repo if you see issues in the documentation (https://github.com/autorope/donkeydocs). I have updated this now.
