### ISSUE TITLE
Presently there is a conflict of the usage of GPIO 13 between the RC Control and the Odometry/encoders

### ISSUE THREAD

**Issue by TCIII** [autorope/donkeycar#923]
A review of the use of GPIO 13 by the RC Control function and the Odometry/encoder function indicates that the Odometry/encoders function is using GPIO 13 (default) as an input while the RC Control function is using GPIO 13 as the Steering PWM output.

Recommend that the author of the Odometry/encoder guide provide suggested alternative inputs that are not presently being used by other DC functions.

**Comment by zlite** [comment]
Solved with [this commit](https://github.com/autorope/donkeydocs/commit/8168bf4c6403a3c7addcb4dfec52900132a5f0d9)
