### ISSUE TITLE
What is the command or code for using RPlidar and YDlidar?

### ISSUE THREAD

**Issue by Choikyungho9** [autorope/donkeycar#944]
I'm using a Raspberry Pi 4B, and I did everything in the order listed in the DOCS.
 
```
# LIDAR
USE_LIDAR = True
LIDAR_TYPE = 'RP' #(RP|YD)
LIDAR_LOWER_LIMIT = 90 # angles that will be recorded. Use this to block out obstructed areas on your car and/or to avoid looking backwards. Note that for the RP A1M8 Lidar, "0" is in the direction of the motor
LIDAR_UPPER_LIMIT = 270
```

I checked all of this.
But I can't check if the rider is being used.
Please tell me how to use it in detail. DOCS is very un-explanatory.

**Comment by Ezward** [comment]
I don't believe there is a template that currently uses the Lidar.  We do have parts, but they are not used by one of the supported templates.  There is this issue to resolve that: https://github.com/autorope/donkeycar/issues/910  and work is being done in this branch https://github.com/autorope/donkeycar/tree/next-gen-lidar-parts .  The goal is to integrate lidar into the standard 'complete' template in a way that uses the lidar to help determine steering and throttle.  Ideally, it would be great to have a SLAM template that uses the lidar or perhaps integrate SLAM into the path_follow template. Perhaps that is a better use of Lidar than in the complete template.  I'm currently working on integrating odometry, pose estimation and speed control into the complete and path_follow templates (issue https://github.com/autorope/donkeycar/issues/921 and branch https://github.com/autorope/donkeycar/tree/921-next-generation-odometer-parts).  Once that is complete I can get back to the Lidar work.
