### ISSUE TITLE
I am getting a Value error in keras.py . Please help.

### ISSUE THREAD

**Issue by Choikyungho9** [autorope/donkeycar#947]
![valueerror](https://user-images.githubusercontent.com/20491139/138211768-8cfc3aa2-d383-4301-bb97-129e77613f60.jpg)

I am using a ps4 joystick connected to Donkey car. But after doing python manage.py drive --model=./model/mypilot.h5 --type=linear , when I change to user mode with the joystick, a value error occurs. I'm not sure what's wrong with this code. Please help me

**Comment by sctse999** [comment]
Are you using a genuine ps4 joystick? I recommend using a F710 or a ps3 joystick. I don't have much experience about the ps4 controller.
