### ISSUE TITLE
Rename Auto modes in Web UI

### ISSUE THREAD

**Issue by zlite** [autorope/donkeycar#972]
Rename "Local Pilot" to "Full Auto"
Rename "Local Angle" to "Auto Steering + Manual Throttle"

(I'm also not sure what the "(d)" means. Maybe remove?

![donkeyUI](https://user-images.githubusercontent.com/18071/146651740-e9d8086c-c3d1-4ab7-99a3-ca156d59ae0a.png)

**Comment by Ezward** [comment]
Addressed in https://github.com/autorope/donkeycar/pull/985
