### ISSUE TITLE
When training, cannot specify filename for myconfig.py

### ISSUE THREAD

**Issue by cfox570** [autorope/donkeycar#976]
I create a set of config files for different purposes. I can specify myconfig filename when running manage.py but not when training.

**Comment by Ezward** [comment]
I like this idea.  One of the most common issues we have is having different configuration when training on the laptop than we have when driving with the donkeycar.  We might even want to require the user to specify a myconfig.py when training; that would make them conscious of the issue.

**Comment by DocGarbanzo** [comment]
I already have the change in one of branches, it's really small, hopefully I'll get to it in the next days.

**Comment by DocGarbanzo** [comment]
Addressed in #997
